### ISSUE TITLE
Rename collections and properties

### ISSUE THREAD

**Issue by nightzirch** [nightzirch/secret-toymaker.backend#3]
In Firestore the following UML is almost correct:

![secret_toymaker_data_structure](https://user-images.githubusercontent.com/1052787/68953106-7fa7b000-07c1-11ea-8bd6-333bfb2f1107.png)

There are a few name changes that needs to be done in the code.
* Event.participations is currently called participants
* Gift.event is currently not implemented

Additionally, I think we should change the name of Participant to something else. User maybe? Same goes for Timebox. I suggest Stage.
* Participant -> User
* Timebox -> Stage

**Comment by Silveress** [comment]
From https://gitlab.com/snippets/1914000

****

### Key points
* Move to async/await for easier readability
  * currently its callback hell witn promises
* make more functions modular to be able to easier expand to future years
  * Can pass teh year in teh request and it will go to that collection
* see if we can persuade Daniel (dsnider) to get ``/v2/account/mail`` up and running to verify if items were sent
  * https://github.com/arenanet/api-cdi/pull/518
* get folks api key.
  * hopefully mail (as above)
  * user access, F2P cannot send mails, only recieve, create seperate pool for them
  * get their UUID, account username can potentially change, rare but cna happen
* Change arounf teh data formats (below) for greater future "proofing"
* If Daniel cannot get the mail endpoint working then when reporting record it on both accounts  in case the reporter is trying to game the system
* Maybe allow previous abusers to join, but they will be put into a pool together
* possibly move the date format to ISO.
  * Native js function
  * easy string compasision of dates

### Data format

Old format
````javascript

let layout = {
  timebox:[
    { SIGNUP:{start:"startTime", end:"endTime"} }
  ],
  participants:[
    {user: "user0", uid:"0123"},
    {user: "user1", uid:"1234"},
    {user: "user2", uid:"2345"}
  ],
  events:[
    {
      2019:[
        {
          participants:[
            {user: "user1", uid:"1234"},
            {user: "user2", uid:"2345"}
          ]
        }
      ]
    }
  ]
}
````

New ideas

````javascript

let layout = {
  // stores all participents over time
  // holds all data related to that user
  participants:[
    {user: "user0", uid:"0123"},
    {user: "user1", uid:"1234"},
    {user: "user2", uid:"2345"},
    {user: "user3", uid:"3456"}
  ],
  events:[
    {
      2019:[
        {
          // store timebox in teh year collection, keeps teh data together
          timebox: { SIGNUP:{start:"startTime", end:"endTime"} },

          // store uid and who they are getting teh gift from
          // oldFromUids is an array of people who failed to get stend a gift
          participants:[
            { uid:"1234", fromUid:"2345", oldFromUids:[ "0123" ] },
            { uid:"2345", fromUid:"3456", oldFromUids:[]  },
            { uid:"3456", fromUid:"1234", oldFromUids:[]  }
          ]
        }
      ]
    }
  ]
}
````
